version: "3.4"
services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - express-api-base
      - db
    networks:
      - combined-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - combined-network

  express-api-base:
    build: ./express-api-base
    command: npm run start
    container_name: express-api-base
    restart: unless-stopped
    environment:
      - DEPLOY_PORT=8001
      - API_HISTORY_PORT=8002
    stdin_open: true
    networks:
      - combined-network

  express-api-history:
    build: ./express-api-history
    command: npm run start
    container_name: express-api-history
    restart: unless-stopped
    environment:
      - DEPLOY_PORT=8002
    stdin_open: true
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge
